# syntax=docker.io/docker/dockerfile:1

FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Salin file yang dibutuhkan untuk instalasi dependencies
COPY package.json yarn.lock ./

# Install dependencies menggunakan yarn
RUN yarn install
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

# Copy node_modules dari tahap deps
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build aplikasi menggunakan yarn
RUN yarn build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production


# Salin juga node_modules agar runtime bisa berjalan
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Tambahkan dep yang dibutuhkan oleh runtime
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json



EXPOSE 3002
ENV PORT=3002
ENV HOSTNAME="0.0.0.0"

# Jalankan Next.js standalone server
CMD ["node", "server.js"]
